services:
  - type: web
    plan: free
    name: Zaid
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn app:app & python3 generator.py
    repo: https://github.com/ITZ-ZAID/Session-bot      
    branch: master
    envVars:
      - key: BOT_TOKEN 
        sync: false    
    autoDeploy: false
